name: FRadioPlayer
options:
  bundleIdPrefix: com.fethica
  deploymentTarget:
    iOS: 9.0
targets:
  FRadioPlayer:
    type: framework
    platform: [iOS]
    sources: Source
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
